Repository getgort/gort, pull requests merged in 2021-07, with the labels that each got.

#43 Inject default envvars into each container as per docs
  adapter/adapter.go
  relay/relay.go
  worker/worker.go
Labels: enhancement

#44 Allow Gort CLI to be run as a command bundle
  client/client-auth.go
  client/client.go
  data/config.go
  worker/worker.go
Labels: bug, enhancement

#34 Add "role list" command.
  cli/role-list.go
  cli/role.go
  client/client-role.go
  dataaccess/dataaccess.go
  dataaccess/memory/role-access.go
  dataaccess/memory/role-access_test.go
  dataaccess/postgres/role-access.go
  dataaccess/postgres/role-access_test.go
  service/role-handlers.go
Labels: enhancement

#56 Standardize command names and help output format
  cli/bootstrap.go
  cli/bundle-disable.go
  cli/bundle-enable.go
  cli/bundle-info.go
  cli/bundle-install.go
  cli/bundle-list.go
  cli/bundle-uninstall.go
  cli/bundle-yaml.go
  cli/bundle.go
  cli/group-add.go
  cli/group-create.go
  cli/group-delete.go
  cli/group-grant.go
  cli/group-info.go
  cli/group-list.go
  cli/group-remove-user.go
  cli/group-remove.go
  cli/group-revoke.go
  cli/group.go
  cli/role-create.go
  cli/role-delete.go
  cli/role-grant.go
  cli/role-list.go
  cli/role-revoke.go
  cli/role.go
  cli/user-create.go
  cli/user-delete.go
  cli/user-info.go
  cli/user-list.go
  cli/user-update.go
  cli/user.go
  client/client-auth.go
  cmd-root.go
Labels: bug

#57 Create a 'hidden' subcommand for hidden CLI commands
  cli/hidden-commands.go
  cli/hidden.go
  cmd-root.go
Labels: enhancement

#72 Create 'gort profile' commands
  .gitignore
  .vscode/settings.json
  cli/profile-create.go
  cli/profile-default.go
  cli/profile-delete.go
  cli/profile-list.go
  cli/profile.go
  client/client-auth.go
  client/client.go
  client/profile.go
  cmd-root.go
Labels: enhancement

#73 Implement `LongDescription` for bundle commands
  bundles/bundle_test.go
  bundles/default.yml
  cli/hidden-command.go
  data/bundle.go
  dataaccess/memory/bundle-access_test.go
  dataaccess/postgres/bundle-access.go
  dataaccess/postgres/bundle-access_test.go
  dataaccess/postgres/postgres-data-access.go
  testing/test-bundle.yml
Labels: bug, enhancement

#76 Remove concept of 'default bundle'
  adapter/adapter.go
  config.yml
  config/bundles.go
  config/config.go
  config/config_test.go
  data/config.go
  service/bundle-handlers.go
Labels: enhancement

#77 Fix profile confusion bug
  client/client.go
Labels: bug

#78 Remove email/password/name args from bootstrap
  cli/bootstrap.go
  client/client-auth.go
Labels: enhancement

#85 Can no longer bootstrap over an existing profile
  cli/bootstrap.go
  client/client-auth.go
  client/client.go
Labels: bug

#87 Add check for empty profile list
  client/profile.go
Labels: bug

#88 Update various `list` subcommands to consistently use the Columnizer
  cli/bundle-list.go
  cli/group-list.go
  cli/permission-list.go
  cli/profile-list.go
  cli/role-list.go
  cli/user-list.go
Labels: enhancement
